development:
  secret_token: "my_secret_token"
  secret_key_base: "abcdef0123456789"


# development:
#   secret_key_base:  asdflkjasdlfewruiyqtuiweuiwedfkj

# test:
#   secret_key_base:  asdflkhasldfhlhaskiotioeuteteuwriotuoyi

# production:
#   secret_key_base: 523lk5h2lkjlj4353453489udfg0es496i6lk4